version: '3'
services:
  postgres:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=weather_forecast_ml_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/database/initial.sql:/docker-entrypoint-initdb.d/initial.sql